FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER app
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["Contracts/Contracts.csproj", "Contracts/"]
COPY ["Users/Users.Presentation/Users.Presentation.csproj", "Users/Users.Presentation/"]
COPY ["Users/Users.Application/Users.Application.csproj", "Users/Users.Application/"]
COPY ["Users/Users.Domain/Users.Domain.csproj", "Users/Users.Domain/"]
COPY ["Users/Users.Infrastructure/Users.Infrastructure.csproj", "Users/Users.Infrastructure/"]

RUN dotnet restore "Users/Users.Presentation/Users.Presentation.csproj"
COPY . .
WORKDIR "/src/Users/Users.Presentation"
RUN dotnet build "Users.Presentation.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Users.Presentation.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Users.Presentation.dll"]
