FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER app
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["Contracts/Contracts.csproj", "Contracts/"]
COPY ["Events/Events.Presentation/Events.Presentation.csproj", "Events/Events.Presentation/"]
COPY ["Events/Events.Application/Events.Application.csproj", "Events/Events.Application/"]
COPY ["Events/Events.Domain/Events.Domain.csproj", "Events/Events.Domain/"]
COPY ["Events/Events.Infrastructure/Events.Infrastructure.csproj", "Events/Events.Infrastructure/"]

RUN dotnet restore "Events/Events.Presentation/Events.Presentation.csproj"
COPY . .
WORKDIR "/src/Events/Events.Presentation"
RUN dotnet build "Events.Presentation.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Events.Presentation.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Events.Presentation.dll"]
